### PR TITLE
call __repr__() on url rather than __str__() to hide password

### LINKED ISSUE #91: version 0.3.9 is printing cleartext passwords to my notebook
I have had to install version `0.3.9` of ipython-sql due to https://github.com/catherinedevlin/ipython-sql/issues/67. But this version prints my sqlalchemy connection string containing username and password, which I certainly do not want in there if I put some of my analyses to github. I can use `%%capture` to circumvent this, but I think this should not be standard behavior in principle.

If there is an easy way to switch this off in version `0.3.9` general, I'd be happy to learn how that works for now.

Thanks!

### PR DESCRIPTION
**Pull request by jstoebel**
calling `__repr__()` rather than `__str__()` on the connection url object hides the password.
this should close #91

### CODE REVIEW

**Comment by jstoebel** [comment]
Since sqlite does not use a password in the connection string we can't test this under the current set up AFAIK. is there an interest in setting up a testing environment with CircleCI or something similar so we can easily run tests against postgres?

**Comment by jstoebel** [comment]
also: for some reason the connection string is sometimes printed out more than once. I am looking into this.

**Comment by jstoebel** [comment]
it looks like the culprit is in `sql.connection.Connection.__init__` , specifically:

```
        self.connections[self.name] = self
        self.connections[str(self.metadata.bind.url)] = self
```
Here it looks like we are mapping the connection's assigned name and its url to the the `Connection` instance. Do we want to maintain both representations of the connection in the connections dictionary? More to the point, do we want to print out both?

**Comment by catherinedevlin** [comment]
Ah, I semi-remember now: the idea was that you'd be able to refer to a connection either by its full connection string, or by an abbreviated version.  That way you could use `%sql (connection)` to switch back to an earlier connection without giving the full connection string.  So, like this (this is on the current `master` branch):

`In [5]: %sql postgresql://passwordy:password@/catherine
Out[5]: 'Connected: passwordy@catherine'

In [6]: %sql sqlite:///mydb.sqlite
Out[6]: 'Connected: @mydb.sqlite'

In [7]: %sql
 * @mydb.sqlite
   passwordy@catherine
   postgresql://passwordy:password@/catherine
 * sqlite:///mydb.sqlite
Out[7]: 'Connected: @mydb.sqlite'

In [8]: %sql passwordy@catherine
Out[8]: 'Connected: passwordy@catherine'`

Can we maintain that capability?

**Comment by jstoebel** [comment]
gotcha, so I guess we're good with that

**Comment by jstoebel** [comment]
do you have any thoughts on how to test for this fix? (see above)

**Pull request closed without merging**
