### PR TITLE
Add syntax coloring support

### PR DESCRIPTION
**Pull request by xiaochuanyu**
See:
http://stackoverflow.com/questions/28703626/ipython-change-input-cell-syntax-highlighting-logic-for-entire-session

### CODE REVIEW

**Comment by catherinedevlin** [comment]
Thank you for this!

I notice that they syntax coloring doesn't seem to kick in until a cell has been successfully executed, which is too bad - since if you make a SQL error, it doesn't apply the coloring, which might help you figure out what your error was.  This is still a good addition, of course.  I'll make a new ticket for that enhancement, and if you happen to know easily how to use it on cells that error out, you can knock that ticket out too.  :)

**Comment by catherinedevlin** [comment]
Created https://github.com/catherinedevlin/ipython-sql/issues/85

**Comment by ViktorQvarfordt** [comment]
This PR must be updated for [ipython 6](https://stackoverflow.com/a/44283352), see my comment in in #41:

Apparently the name of the property `config_defaults` has changed to `options_default`, so the new version is:
```python
from IPython.display import display_javascript
js = "IPython.CodeCell.options_default.highlight_modes['magic_sql'] = {'reg':[/^%%sql/]};"
display_javascript(js, raw=True)
```

**Comment by ViktorQvarfordt** [comment]
Also, don't we want syntax highlighting also for inline sql?

```py
js += "IPython.CodeCell.options_default.highlight_modes['magic_sql'] = {'reg':[/^%sql/]};"
```

**Pull request merged**
