### PR TITLE
Adding ClickHouse to autocommit blacklist

### PR DESCRIPTION
**Pull request by feriat**
Fixing #103 by adding a blacklist of dialects that are restricted from using autocommit

### CODE REVIEW

**Comment by RemiTurpaud** [comment]
Great idea! I was just about to do the same with `teradata`...
The theoretical risk though is that you may be able to change this transaction setting by default or during the session. So this could be a bit shaky.

If the intent for this code block is to auto commit, I wonder if forcing `autocommit=True`  in the session execution above (and letting SQLAlchemy manage this) wouldn't simply do the job...

**Comment by catherinedevlin** [comment]
A belated thank you to you both!

@RemiTurpaud, everything about autocommit is hacky to begin with, and I'd love any further research into what backends should and should not use it, or whether there's a different way entirely.

PRs on this package are teaching me about database engines I didn't know existed!

**Comment by RemiTurpaud** [comment]
Hi @catherinedevlin , on the other hand, this is quite simple and easy to maintain in the way it is currently defined. I will try to experiment with a few options when I get some time, and see if it works and actually simplifies the code...
Meanwhile, I have added Teradata to the dialect list, that should have autocommit by default - PR #115.

**Comment by ryn9** [comment]
I think the original issue is resolved - but there appears to be an issue with leveraging the 'native' interface.

=====THIS WORKS=====
%load_ext sql
%sql clickhouse://default:@10.1.1.2:8123/default
%%sql
SHOW DATABASES

=====THIS DOES NOT=====
%load_ext sql
%sql clickhouse+native://default:@10.1.1.2:8123/default
%%sql
SHOW DATABASES

relevant packages:
clickhouse-driver-0.0.17
clickhouse-sqlalchemy-0.0.10
ipython-sql-0.3.9
sqlalchemy-1.2.17

Please let me know what other information you would like to see to help troubleshoot.

**Comment by ryn9** [comment]
For whatever its worth - I tried to patch run.py with the following:
_COMMIT_BLACKLIST_DIALECTS = ('mssql', 'clickhouse', 'teradata', 'clickhouse+native')
I did not have any luck

**Pull request merged**
